### ISSUE TITLE
Lecture exercises

### ISSUE THREAD

**Issue by iturn** [cryptoeconomics-study/website#17]
First of all great work so far on this website. 
What type of exercises do we want in the lectures? Would they be for example code or multiple choice?

**Comment by karlfloersch** [comment]
Hmm! Good question. So for instance on https://cryptoeconomics.study/lectures/chapter-01-1.html I feel like it could be great to have a couple coding exercises which have you sign a message & check the signature, and maybe hash a document or something.

That said, I think there's totally a place for multiple choice and might be ideal to have both code and multiple choice. The only question with multiple choice is I haven't yet thought about how to integrate multiple choice questions into the website. I'm sure it wouldn't be hard though and I'd love if someone could help out with that.

As for the questions themselves, once I finish a few more lectures I might look back and try to come up with some questions (both multiple choice & coding questions), but in the mean time it would be awesome if someone who watches the lecture & thinks they understand the sticking points in the content could come up with some good ones that I might not even think of.

**Comment by iturn** [comment]
Ok great i'll come up with some questions then.

**Comment by burrrata** [comment]
> I feel like it could be great to have a couple coding exercises which have you sign a message & check the signature, and maybe hash a document or something.

[We did that and it's live!](https://cryptoeconomics.study/docs/en/sync/1.1-code-challenge)

Also have a bunch of review questions that we don't have time to do anything with here. @iturn If you came up with questions that you want to add or have ideas on how review questions could serve the community please add them to this Issue :)
- https://github.com/cryptoeconomics-study/dao/issues/7

Closing this Issue because it's quite old and community projects are being moved to the [dao repo](https://github.com/cryptoeconomics-study/dao)
